version: "3.9"
services:
  web:
    image: 'postgresgoapp:latest'
    build:
      context: .
    container_name: app
    depends_on:
        - db
    ports:
      - "8080:8080"
    environment:
        DBPORT: 5432
        DBHOST: db
        DBUSER: postgres
        DBPASS: dbpassword
        DBNAME: peopledatabase
  db:
    image: 'postgres:13.1-alpine'
    container_name: postgres
    healthcheck:
        test: [ "CMD", "pg_isready", "-q", "-d", "peopledatabase", "-U", "postgres" ]
        timeout: 45s
        interval: 10s
        retries: 10
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=peopledatabase
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/