apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "postgresgoapp.fullname" . }}
  labels:
    {{- include "postgresgoapp.labels" . | nindent 4 }}
data:
{{- toYaml .Values.envConfig | nindent 4 }}